### ISSUE TITLE
Hibernate @JdbcTypeCode need support

### ISSUE THREAD

**Issue by solomon-maeng** [IceBlizz6/querydsl-ksp#7] opened 2024-10-11 04:45 UTC
There is a case where `@JdbcTypeCode` is used as an entity field like below.

```kotlin
@Entity
@Table(name = "order_logs")
class OrderLog(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0L,
    @JdbcTypeCode(SqlTypes.JSON)
    val metadata: Map<String, Any?>
)
```
I have the following error:
`[ksp] java.lang.IllegalStateException: Error processing kr.co.sample.domain.OrderLog.metadata: Type was not recognised, This may be an entity that has not been annotated with @Entity, or maybe you are using javax instead of jakarta.`

need support for the `@JdbcUserType` annotation.

**Comment by IceBlizz6** [comment] 2024-10-11 06:25
Thank you for reporting this.

It seems like the problem is that kotlin.Any isn't supported in my project.
I tried to add support for kotlin.Any now, please try this build:
ksp("com.github.IceBlizz6:querydsl-ksp:d2566c39dd")

@JdbcTypeCode is not being picked up, and i'm not sure if we need to add support for this explicitly unless it changes behavior of how Q classes should be generated.

The code samples you supplied is working on my machine now.

You should be aware that running KSP again after a failure may trigger this bug:
https://github.com/google/ksp/issues/2072#issuecomment-2398510160
it's technically fixed, but the fix has not been released yet.

Please let me know if my build is working,
in which case i will release this in next official version.

**Comment by IceBlizz6** [comment] 2024-10-15 08:25
Hey, 
Were you able to see if the build worked for you?

**Comment by solomon-maeng** [comment] 2024-10-31 04:28
@IceBlizz6 
I'm sorry for the delayed response. As a result of working with the version of the commit you provided, the build & compile was successful, and most of the test codes worked well.

However, some test codes failed.

The common error in the failed test cases was an error that occurred in a method returning a List<Long> type for the Id column of the Entity, as shown below:

Caused by: java.lang.IllegalArgumentException: Unsupported target type : long
    at com.querydsl.core.util.MathUtils.cast(MathUtils.java:86)
    at com.querydsl.core.types.dsl.NumberExpression.cast(NumberExpression.java:178)
    at com.querydsl.core.types.dsl.NumberExpression.gt(NumberExpression.java:337)


Regarding the above error, after looking up on StackOverflow, I found a suggestion. It seems we might need to modify the following code in the Kotlin Class generated by KSP:

public val id: NumberPath<Long> = createNumber("id", kotlin.Long::class.java) # I think we should try changing this to kotlin.Long::class.javaObjectType.

**Comment by IceBlizz6** [comment] 2024-11-01 04:17
No worries about the delay.
I'm not able to figure out how to reproduce this issue.
Would you be able to provide a code sample?
include a simple entity and the query that throws the error.

**Comment by solomon-maeng** [comment] 2024-11-01 11:44
@IceBlizz6 I am sharing a sample example that reproduces the issue I experienced.

https://github.com/solomon-maeng/querydsl-ksp-exam/blob/master/src/main/kotlin/com/rebwon/querydslkspsample/CompanyRepo.kt

**Comment by IceBlizz6** [comment] 2024-11-02 03:16
I was able to reproduce the issue.
I added the fix into this commit, please try it.
ksp("com.github.IceBlizz6:querydsl-ksp:f864a7793f")

**About the imports:**

There are several options here

Option 1) Reference by class name
```kotlin
jpaQueryFactory.select(QCompany.company.id)
	.from(QCompany.company)
	.where(QCompany.company.id.gt(nextId))
	.limit(size)
	.orderBy(QCompany.company.id.asc())
	.fetch()
```

Option 2) Make variable
```kotlin
val company = QCompany.company
jpaQueryFactory.select(company.id)
	.from(company)
	.where(company.id.gt(nextId))
	.limit(size)
	.orderBy(company.id.asc())
	.fetch()
```

Option 3) Import
```
import com.rebwon.querydslkspsample.QCompany.Companion.company
...
jpaQueryFactory.select(company.id)
	.from(company)
	.where(company.id.gt(nextId))
	.limit(size)
	.orderBy(company.id.asc())
	.fetch()
```

Personally i use option 1 or 2, i never use 3.
Are there other options which you may have preferred?

**Comment by solomon-maeng** [comment] 2024-11-02 06:26
@IceBlizz6 

With the changes you provided, both the build and testing were successful. Thank you for the prompt revision.

Regarding the import of QClass, I prefer option 2. However, the project I am currently developing is entirely implemented with option 3, regardless of my preference.

If options 1 and 2 are used, there would be no need to use import statements when referencing QClass, thus avoiding problems related to import. However, those who mainly use option 3 might be reluctant to change import references.

That said, this is just my opinion, and I hope more people can use this library and actively exchange feedback.

**Comment by IceBlizz6** [comment] 2024-11-02 11:55
I'm not sure if there are any other solutions in Kotlin, i think as long as we want a global variable then it would have to be placed into a companion object.

I released the aforementioned commit as official version 0.0.4
I will close this issue now as i think both your issues were solved, feel free to reopen if you experience problems with these solutions.

**Closed by IceBlizz6** 2024-11-02 11:55 UTC
